### ISSUE TITLE
xcode 编译

### ISSUE THREAD

**Issue by Demonsword27** [China-Robin/react-native-realm-sync-storage#1]
xcode 编译始终处于 RealmJS Running 1 of 1 custom shell scripts 卡住了。。。

**Comment by China-Robin** [comment]
@Wbqqqq 你好，请问你是否执行了react-native link realm如果执行了，请在控制台中执行react-native run-ios这个语句会去下载realm库，过程可能会比较长的时间，因为这个库的大小为200MB左右，大概需要30分钟左右
